/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author harga
 */
public class datereport extends javax.swing.JFrame {

    /**
     * Creates new form datereport
     */
    public datereport() {
        initComponents();
        this.setDefaultCloseOperation(datereport.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbreport = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        txtfrom = new com.toedter.calendar.JDateChooser();
        txtto = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Veiw Report :");

        cmbreport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Member", "Employee", "Employee Payment", "Expense", "Fees" }));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("SHOW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtfrom.setDateFormatString("yyyy-MM-dd");

        txtto.setDateFormatString("yyyy-MM-dd");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("From :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText(" To :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Date-Wise Report");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtto, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtfrom, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(cmbreport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cmbreport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtfrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       if(cmbreport.getSelectedIndex()==0){
            Map param = new HashMap();
              
             param.put("date1",txtfrom.getDate());
               param.put("date2",txtto.getDate());
             
              JasperReport ir;
                try
               {
                     ir = JasperCompileManager.compileReport("E:\\JSP\\GymManagementSystem\\src\\reports\\membership2.jrxml");
                     
                     JasperPrint ip ;
                      ip = JasperFillManager.fillReport(ir, param,DataAccess.con);
                       JasperViewer.viewReport(ip);
                 } catch (JRException ex)
                 {
                    JOptionPane.showMessageDialog(null, ex);
                }
       }
       else if(cmbreport.getSelectedIndex()==1){
            Map param = new HashMap();
              
             param.put("date1",txtfrom.getDate());
               param.put("date2",txtto.getDate());
             
              JasperReport ir;
                try
               {
                     ir = JasperCompileManager.compileReport("E:\\JSP\\GymManagementSystem\\src\\reports\\employee2.jrxml");
                     
                     JasperPrint ip ;
                      ip = JasperFillManager.fillReport(ir, param,DataAccess.con);
                       JasperViewer.viewReport(ip);
                 } catch (JRException ex)
                 {
                    JOptionPane.showMessageDialog(null, ex);
                }
       }else if(cmbreport.getSelectedIndex()==2){
            Map param = new HashMap();
              
             param.put("date1",txtfrom.getDate());
               param.put("date2",txtto.getDate());
             
              JasperReport ir;
                try
               {
                     ir = JasperCompileManager.compileReport("E:\\JSP\\GymManagementSystem\\src\\reports\\emoloyeepayment2.jrxml");
                     
                     JasperPrint ip ;
                      ip = JasperFillManager.fillReport(ir, param,DataAccess.con);
                       JasperViewer.viewReport(ip);
                 } catch (JRException ex)
                 {
                    JOptionPane.showMessageDialog(null, ex);
                }
       }else if(cmbreport.getSelectedIndex()==3){
            Map param = new HashMap();
              
             param.put("date1",txtfrom.getDate());
               param.put("date2",txtto.getDate());
             
              JasperReport ir;
                try
               {
                     ir = JasperCompileManager.compileReport("E:\\JSP\\GymManagementSystem\\src\\reports\\expense2.jrxml");
                     
                     JasperPrint ip ;
                      ip = JasperFillManager.fillReport(ir, param,DataAccess.con);
                       JasperViewer.viewReport(ip);
                 } catch (JRException ex)
                 {
                    JOptionPane.showMessageDialog(null, ex);
                }
       }else if(cmbreport.getSelectedIndex()==4){
            Map param = new HashMap();
              
             param.put("date1",txtfrom.getDate());
               param.put("date2",txtto.getDate());
             
              JasperReport ir;
                try
               {
                     ir = JasperCompileManager.compileReport("E:\\JSP\\GymManagementSystem\\src\\reports\\fees2.jrxml");
                     
                     JasperPrint ip ;
                      ip = JasperFillManager.fillReport(ir, param,DataAccess.con);
                       JasperViewer.viewReport(ip);
                 } catch (JRException ex)
                 {
                    JOptionPane.showMessageDialog(null, ex);
                }
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datereport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datereport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datereport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datereport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            DataAccess.dbConnect();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datereport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbreport;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private com.toedter.calendar.JDateChooser txtfrom;
    private com.toedter.calendar.JDateChooser txtto;
    // End of variables declaration//GEN-END:variables
}
