/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import java.awt.event.ActionListener;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;



/**
 *
 * @author harga
 */
public class feesform extends javax.swing.JFrame {
   Statement st;
    ResultSet rs;
    String fdate;
    /**
     * Creates new form feesform
     */
    public feesform() {
        initComponents();
        BindTable();
        GetMaxID();
        BindCombo();
         this.setDefaultCloseOperation(membershipform.DISPOSE_ON_CLOSE); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtfid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtfamt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtfdamt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtnamt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cmbmop = new javax.swing.JComboBox<>();
        btnsave = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        btncan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cmbmid = new javax.swing.JComboBox<>();
        txtfdate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 50)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vision Of Fitness");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Fees Information");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Fees ID");

        txtfid.setForeground(new java.awt.Color(204, 204, 204));
        txtfid.setEnabled(false);
        txtfid.setFocusable(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Member Name");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Fees Date");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText(" Total Amount");

        txtfamt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfamtActionPerformed(evt);
            }
        });
        txtfamt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfamtKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Return Amount");

        txtfdamt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfdamtKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Amount Paid");

        txtnamt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnamtFocusLost(evt);
            }
        });
        txtnamt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamtActionPerformed(evt);
            }
        });
        txtnamt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnamtKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Mode of Payment");

        cmbmop.setBackground(new java.awt.Color(204, 204, 204));
        cmbmop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mode Of Payment", "Online", "Cash" }));
        cmbmop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbmopActionPerformed(evt);
            }
        });

        btnsave.setBackground(new java.awt.Color(0, 0, 255));
        btnsave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsave.setForeground(new java.awt.Color(204, 204, 204));
        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btndel.setBackground(new java.awt.Color(255, 0, 0));
        btndel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btndel.setForeground(new java.awt.Color(204, 204, 204));
        btndel.setText("DELETE");
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });

        btncan.setBackground(new java.awt.Color(0, 0, 0));
        btncan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btncan.setForeground(new java.awt.Color(204, 204, 204));
        btncan.setText("CLEAR");
        btncan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncanActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        cmbmid.setBackground(new java.awt.Color(204, 204, 204));
        cmbmid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "member" }));
        cmbmid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbmidActionPerformed(evt);
            }
        });

        txtfdate.setDateFormatString("yyyy/MM/dd");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1106, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnsave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncan))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtfid, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtnamt)
                                .addComponent(txtfdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbmop, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtfdamt, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtfamt)
                            .addComponent(jLabel7)
                            .addComponent(cmbmid, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtfid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbmid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtfamt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfdamt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnamt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbmop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsave)
                            .addComponent(btndel)
                            .addComponent(btncan)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 207, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
DataAccess d=new DataAccess();

private void GetMaxID() {
        try {
            st = DataAccess.con.createStatement();
            rs = st.executeQuery("select ifnull(max(FeeID+1),1) as id from feesmaster");
            if (rs.next()) {
                int id = rs.getInt(1);
                txtfid.setText(Integer.toString(id));
            }
            st.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }
 void search(int id) {
        try {
            String str = "SELECT FeeID,FeesDate,memberid,Amount,DueAmount,netamount,modeofpayment FROM feesmaster WHERE (FeeID =" + id + ")";
            PreparedStatement pst = DataAccess.con.prepareStatement(str);
            rs = pst.executeQuery();
            if (rs.next()) {
                txtfid.setText(String.valueOf(rs.getInt("FeeID")));
                cmbmid.setSelectedItem(rs.getString("memberid"));
                txtfamt.setText((rs.getString("Amount")));
               txtfdamt.setText((rs.getString("DueAmount")));
                txtnamt.setText(rs.getString("netamount"));
                txtfdate.setDate(rs.getDate("feesdate"));
                cmbmop.setSelectedItem(rs.getString("modeofpayment"));

                //btnDelete.setEnabled(true);
                btnsave.setText("UPDATE");
            }
        } catch (NumberFormatException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }
 
 
    void Clear() {
        
        txtfamt.setText("");
        txtnamt.setText("");
        txtfdamt.setText("");
        txtfid.setText("");

        GetMaxID();
        btndel.setEnabled(false);
        btnsave.setText("Save");
    }
    
    private void BindTable() {
        try {
            String sql = "select feesmaster.FeeID,feesmaster.FeesDate,membershipmaster.membername ,membershipmaster.memberid,feesmaster.Amount,feesmaster.DueAmount,feesmaster.netamount,feesmaster.modeofpayment from feesmaster inner join membershipmaster on membershipmaster.memberid=feesmaster.FeeID";
            st = DataAccess.con.createStatement();
            rs = st.executeQuery(sql);
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));//memberid membername
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }
    public void BindCombo()
	{		
		try
                {
                    String name="";int itemID;
                    boolean cnt=true;
                    Vector comboboxitem=new Vector();
                     st =DataAccess.con.createStatement();
                    ResultSet rs = st.executeQuery("SELECT memberid,membername FROM  membershipmaster");    
                    comboboxitem.add(new Item(0,"Select Item"));
                    while(rs.next())
                    {
                         cnt=false;
                        itemID=rs.getInt("memberid");
                        name=rs.getString("membername");
                        comboboxitem.add(new Item(itemID, name));
                    }
                    if(cnt)
                    {
                       comboboxitem.add(new Item(0,"No Items Avilable"));  
                    }

                     DefaultComboBoxModel model =new DefaultComboBoxModel(comboboxitem);
                     cmbmid.setModel(model);
                    cmbmid.addActionListener((ActionListener) this);

                }
                catch(Exception ex)
                {
                  //  JOptionPane.showMessageDialog(null, ex);
                }
	}    
 
    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
        // TODO add your handling code here:
        try {
            st = DataAccess.con.createStatement();
            String sql = "DELETE FROM feesmaster WHERE FeeID = " + txtfid.getText() + "";
            st.executeUpdate(sql);

            Clear();
            BindTable();
            //BindSearch();
            JOptionPane.showMessageDialog(null, "Record Deleted Sucessfully", "Fess Master", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException e1) {

            JOptionPane.showMessageDialog(null, "You can't delete the record....", "Fess Master", JOptionPane.INFORMATION_MESSAGE);
        }
        
    
    }//GEN-LAST:event_btndelActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
   SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        fdate = sdf.format(txtfdate.getDate());
        try {

            if (btnsave.getText().equalsIgnoreCase("Save")) {
                st = DataAccess.con.createStatement();

                st.executeUpdate("insert into feesmaster(FeesDate,Amount,memberid,DueAmount,netamount,modeofpayment)values ('"+fdate+ "','" + txtfamt.getText() + "','" + cmbmid.getSelectedIndex() + "','" + txtnamt.getText() + "','" + txtfdamt.getText() + "','" + cmbmop.getSelectedItem() + "')");

                JOptionPane.showMessageDialog(null, "Record Saved Sucessfully............", "Fees Master", JOptionPane.INFORMATION_MESSAGE);
                st.close();
                BindTable();
            } else {
                st = DataAccess.con.createStatement();

                st.executeUpdate("UPDATE feesmaster SET FeesDate='" + fdate + "',Amount='" + txtfamt.getText() + "',DueAmount ='" + txtfdamt.getText() + "',netamount ='" + txtfamt.getText() + "',modeofpayment='" + cmbmop.getSelectedItem() + "' WHERE (FeeID =" + txtfid.getText() + ")");
                JOptionPane.showMessageDialog(null, "Record Updated Sucessfully.............", "Fees Master", JOptionPane.WARNING_MESSAGE);
                st.close();

                BindTable();
                btnsave.setText("Save");
            }
            //Clear();BindTable();BindSearch();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString(), "Fees Master", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btncanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncanActionPerformed
        // TODO add your handling code here:
       Clear();
    }//GEN-LAST:event_btncanActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        String tblclick = (jTable1.getModel().getValueAt(row, 0).toString());
        int id = Integer.parseInt(tblclick);
        // JOptionPane.showMessageDialog(null, String.valueOf(row));
        search(id);
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtfamtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfamtKeyTyped
        // TODO add your handling code here:
       // d.EnterFloating(evt, txtfamt);
    }//GEN-LAST:event_txtfamtKeyTyped

    private void txtnamtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnamtKeyTyped
        // TODO add your handling code here:
       // d.EnterFloating(evt, txtnamt);
    }//GEN-LAST:event_txtnamtKeyTyped

    private void txtfdamtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfdamtKeyTyped
        // TODO add your handling code here:
        //d.EnterFloating(evt, txtfdamt);
    }//GEN-LAST:event_txtfdamtKeyTyped

    private void txtfamtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfamtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfamtActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
          Date date = new Date();
        txtfdate.setDate(date);

        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDateTime now = LocalDateTime.now();
        fdate = dtf.format(now);

        Calendar c = Calendar.getInstance();
        int timeOfDay = c.get(Calendar.HOUR_OF_DAY);

        
        GetMaxID();
        BindTable();
    }//GEN-LAST:event_formWindowOpened

    private void txtnamtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnamtFocusLost
        // TODO add your handling code here:
           /*float total,paidamt,balanceamt;
        total=Float.parseFloat(txtfamt.getText());
        if(txtnamt.getText().equals("")){
           paidamt=0;
        }
        else{}{
        paidamt=Float.parseFloat(txtnamt.getText());
    }
        balanceamt=total-paidamt;
        txtfdamt.setText(String.valueOf(balanceamt));*/
    }//GEN-LAST:event_txtnamtFocusLost

    private void cmbmidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbmidActionPerformed
        // TODO add your handling code here:
         try {
            String sql = "select feesmaster.FeeID,feesmaster.FeesDate,membershipmaster.membername,feesmaster.Amount,feesmaster.DueAmount,feesmaster.netamount,feesmaster.modeofpayment from feesmaster inner join membershipmaster on membershipmaster.memberid=feesmaster.FeeID";
            st = DataAccess.con.createStatement();
            rs = st.executeQuery(sql);
            //jTable1.setModel(DbUtils.resultSetToTableModel(rs));//memberid
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
    }//GEN-LAST:event_cmbmidActionPerformed

    private void cmbmopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbmopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbmopActionPerformed

    private void txtnamtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamtActionPerformed
        // TODO add your handling code here:
        int a=Integer.parseInt( txtnamt.getText());
        int b=Integer.parseInt( txtfamt.getText());
        int c=a-b;
        
         txtfdamt.setText(Double.toString(c));
    }//GEN-LAST:event_txtnamtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(feesform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(feesform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(feesform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(feesform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         DataAccess.dbConnect();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new feesform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncan;
    private javax.swing.JButton btndel;
    private javax.swing.JButton btnsave;
    private javax.swing.JComboBox<String> cmbmid;
    private javax.swing.JComboBox<String> cmbmop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtfamt;
    private javax.swing.JTextField txtfdamt;
    private com.toedter.calendar.JDateChooser txtfdate;
    private javax.swing.JTextField txtfid;
    private javax.swing.JTextField txtnamt;
    // End of variables declaration//GEN-END:variables
}
