/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import forms.DataAccess;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author harga
 */
public class loginform extends javax.swing.JFrame {
public  Statement st;
    public  ResultSet rs;
    /**
     * Creates new form     
     */
    public loginform() {
       initComponents();
       this.setSize(890,590);this.setResizable(false);
       this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
       // Already there
   // this.setExtendedState(this.MAXIMIZED_BOTH);
        //PathologyLabManagementSystem.dbConnect();
        this.setLocationRelativeTo(null);
        txtuname.setBackground(new java.awt.Color(0,0,0,1));
//        jLabel5.setBackground(new java.awt.Color(0,0,0,1));
        btnlog.setBackground(new java.awt.Color(0,0,0,1));


    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtuname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnlog = new javax.swing.JButton();
        btnf = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtpsw = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 80)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vision Of Fitness");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 888, 70));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Caladea", 1, 40)); // NOI18N
        jLabel2.setText("LOGIN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Username");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));

        txtuname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtuname.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtuname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtunameActionPerformed(evt);
            }
        });
        jPanel1.add(txtuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 200, 30));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));

        btnlog.setBackground(new java.awt.Color(0, 0, 0));
        btnlog.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnlog.setForeground(new java.awt.Color(204, 204, 204));
        btnlog.setText("LOGIN");
        btnlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogActionPerformed(evt);
            }
        });
        btnlog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnlogKeyPressed(evt);
            }
        });
        jPanel1.add(btnlog, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, -1, -1));

        btnf.setBackground(new java.awt.Color(0, 0, 0));
        btnf.setForeground(new java.awt.Color(255, 255, 255));
        btnf.setText("ForgetPassword?");
        btnf.setBorderPainted(false);
        btnf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfActionPerformed(evt);
            }
        });
        jPanel1.add(btnf, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 122, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("CREATE USER");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 110, -1));

        txtpsw.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtpsw.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtpsw, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 200, 30));

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox1.setText("Show Password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1131, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtunameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtunameActionPerformed

    private void btnlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogActionPerformed
                try

        {
            if(txtuname.getText().equals("") || txtpsw.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Enter Username and password","Login",JOptionPane.WARNING_MESSAGE);
            }
            else
            {
                // st=PathologyLabManagementSystem.con.createStatement();
                try
                {
                    String   str="SELECT  username,password FROM  usermaster WHERE (username = '"+txtuname.getText()+"') AND (password = '"+txtpsw.getText()+"')";
                    PreparedStatement    pst =DataAccess.con.prepareStatement(str);
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                        mainform frm=new mainform();
                        frm.setVisible(true);
                        mainform.main(null);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Enter valid User name and password","Login",JOptionPane.WARNING_MESSAGE);
                        txtuname.setText("");
                        txtpsw.setText("");

                    }
                }
                catch(Exception ex)

                {
                    JOptionPane.showMessageDialog(null, ex,"Login",JOptionPane.WARNING_MESSAGE);
                }
            }

        }
        catch(HeadlessException ex)
        {
            //JOptionPane.showMessageDialog(null, ex.toString(),"Login",JOptionPane.WARNING_MESSAGE);
            JOptionPane.showMessageDialog(null, "Enter valid User name and password","Login",JOptionPane.WARNING_MESSAGE);        }
    }//GEN-LAST:event_btnlogActionPerformed

    private void btnfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfActionPerformed
        // TODO add your handling code here:
         forgetpass f = new forgetpass();
        this.dispose();
        f.setVisible(true);
    }//GEN-LAST:event_btnfActionPerformed

    private void btnlogKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnlogKeyPressed
        // TODO add your handling code here:
        try
        {
            if(txtuname.getText().equals("") || txtpsw.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Enter Username and password","Login",JOptionPane.WARNING_MESSAGE);
            }
            else
            {
                // st=PathologyLabManagementSystem.con.createStatement();
                try
                {
                    String   str="SELECT  username,password FROM  usermaster WHERE (username = '"+txtuname.getText()+"') AND (password = '"+txtpsw.getText()+"')";
                    PreparedStatement    pst =DataAccess.con.prepareStatement(str);
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                        mainform frm=new mainform();
                        //mainform m=new mainform();
                        //m.setVisible(false);
                        
                        frm.setVisible(true);
                        mainform.main(null);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Enter valid User name and password","Login",JOptionPane.WARNING_MESSAGE);
                        txtuname.setText("");
                        txtpsw.setText("");

                    }
                }
                catch(Exception ex)

                {
                    JOptionPane.showMessageDialog(null, ex,"Login",JOptionPane.WARNING_MESSAGE);
                }
            }

        }
        catch(HeadlessException ex)
        {
            //JOptionPane.showMessageDialog(null, ex.toString(),"Login",JOptionPane.WARNING_MESSAGE);
            JOptionPane.showMessageDialog(null, "Enter valid User name and password","Login",JOptionPane.WARNING_MESSAGE);        }
        
    }//GEN-LAST:event_btnlogKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        createuser p = null;
    try {
        p = new createuser();
    } catch (SQLException ex) {
        Logger.getLogger(loginform.class.getName()).log(Level.SEVERE, null, ex);
    }
        p.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected())
        {
            txtpsw.setEchoChar((char)0);
        }
        else{
            txtpsw.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
DataAccess.dbConnect();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnf;
    private javax.swing.JButton btnlog;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtpsw;
    private javax.swing.JTextField txtuname;
    // End of variables declaration//GEN-END:variables
}
