/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import java.awt.Color;
import javax.swing.JFrame;
import forms.DataAccess;
import javax.swing.JOptionPane;

/**
 *
 * @author harga
 */
public class mainform extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public mainform() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        employeedetails = new javax.swing.JMenuItem();
        memdet = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        fdet = new javax.swing.JMenuItem();
        emppay = new javax.swing.JMenuItem();
        expdet = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        packagedet = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        cpass = new javax.swing.JMenuItem();
        ext = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 204));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\pavan gym.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-310, -320, -1, -1));

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setForeground(new java.awt.Color(204, 204, 204));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar1.setMinimumSize(new java.awt.Dimension(293, 53));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(293, 53));

        jMenu1.setText("Master");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        employeedetails.setText("Employee Details");
        employeedetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeedetailsActionPerformed(evt);
            }
        });
        jMenu1.add(employeedetails);

        memdet.setText("Member Details");
        memdet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memdetActionPerformed(evt);
            }
        });
        jMenu1.add(memdet);

        jMenuItem1.setText("Equipment Details");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Transaction");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        fdet.setText("Fees Details");
        fdet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fdetActionPerformed(evt);
            }
        });
        jMenu2.add(fdet);

        emppay.setText("Employee Payment");
        emppay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emppayActionPerformed(evt);
            }
        });
        jMenu2.add(emppay);

        expdet.setText("Expense Details");
        expdet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expdetActionPerformed(evt);
            }
        });
        jMenu2.add(expdet);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Package");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        packagedet.setText("Package Details");
        packagedet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packagedetActionPerformed(evt);
            }
        });
        jMenu3.add(packagedet);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Setting");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        cpass.setText("Get Password");
        cpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpassActionPerformed(evt);
            }
        });
        jMenu4.add(cpass);

        ext.setText("EXIT");
        ext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extActionPerformed(evt);
            }
        });
        jMenu4.add(ext);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Login");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Login Back");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void memdetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memdetActionPerformed
        // TODO add your handling code here:
        membershipform p=new membershipform();
//        mainform m=setVisible(true);
        p.setVisible(true);
    }//GEN-LAST:event_memdetActionPerformed

    private void expdetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expdetActionPerformed
        // TODO add your handling code here:
        expenseform e=new expenseform();
        e.setVisible(true);
    }//GEN-LAST:event_expdetActionPerformed

    private void extActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_extActionPerformed

    private void employeedetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeedetailsActionPerformed
        // TODO add your handling code here:
        Employee e = new Employee();
        e.setVisible(true);
    }//GEN-LAST:event_employeedetailsActionPerformed

    private void emppayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emppayActionPerformed
        // TODO add your handling code here:
         employeepaymentform  ep = new employeepaymentform();
        ep.setVisible(true);
    }//GEN-LAST:event_emppayActionPerformed

    private void fdetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fdetActionPerformed
        // TODO add your handling code here:
        feesform f=new feesform();
        f.setVisible(true);
    }//GEN-LAST:event_fdetActionPerformed

    private void packagedetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packagedetActionPerformed
        // TODO add your handling code here:
        packagesform pf=new packagesform();
        pf.setVisible(true);
    }//GEN-LAST:event_packagedetActionPerformed

    private void cpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpassActionPerformed
        // TODO add your handling code here:
        forgetpass fp=new forgetpass();
        fp.setVisible(true);
    }//GEN-LAST:event_cpassActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //OptionPane.showMessageDialog(null, "hhhhhhh");
        //}// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
           equipment ep=new equipment();
        ep.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:
        
        loginform ln=new loginform();
        
        mainform mn=new mainform();
        mn.setVisible(false);
        ln.setVisible(true);
        
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         loginform ln=new loginform();
        
       // mainform mn=new mainform();
        //mn.setVisible(false);
        setVisible(false);
        ln.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cpass;
    private javax.swing.JMenuItem employeedetails;
    private javax.swing.JMenuItem emppay;
    private javax.swing.JMenuItem expdet;
    private javax.swing.JMenuItem ext;
    private javax.swing.JMenuItem fdet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem memdet;
    private javax.swing.JMenuItem packagedet;
    // End of variables declaration//GEN-END:variables
}
