/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.Month;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
import javax.swing.text.PlainDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author harga
 */
public class membershipform extends javax.swing.JFrame {

    Statement st;
    ResultSet rs;
    String doj;
    String dob;
    String Length;

    /**
     * Creates new form
     */
    public membershipform() {
        initComponents();
        BindTable();
        GetMaxID();
        BindCombo();
        this.setDefaultCloseOperation(membershipform.DISPOSE_ON_CLOSE);
        String length = txtmcon.getText();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtmid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtmname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmdw = new javax.swing.JSpinner();
        cmdh = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtmcon = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        btncan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cmbpid = new javax.swing.JComboBox<>();
        cmbval = new javax.swing.JComboBox<>();
        txtdate = new com.toedter.calendar.JDateChooser();
        txtdoj = new com.toedter.calendar.JDateChooser();
        lbl1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vision Of Fitness");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Membership");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Member ID");

        txtmid.setForeground(new java.awt.Color(255, 0, 0));
        txtmid.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Member Name");

        txtmname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmnameKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Date Of Joining");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("DOB");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Weight");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Height");

        cmdw.setModel(new javax.swing.SpinnerNumberModel(35, 35, null, 1));
        cmdw.setValue(40);

        cmdh.setModel(new javax.swing.SpinnerNumberModel(150, 145, null, 1));
        cmdh.setValue(150);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("kg");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("cm");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText(" Package Name");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Contact No");

        txtmcon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtmconFocusLost(evt);
            }
        });
        txtmcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmconActionPerformed(evt);
            }
        });
        txtmcon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmconKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmconKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmconKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Email");

        txtemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtemailFocusLost(evt);
            }
        });
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Validity");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Months");

        btnsave.setBackground(new java.awt.Color(0, 0, 255));
        btnsave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsave.setForeground(new java.awt.Color(204, 204, 204));
        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btndel.setBackground(new java.awt.Color(255, 0, 0));
        btndel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btndel.setForeground(new java.awt.Color(204, 204, 204));
        btndel.setText("DELETE");
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });

        btncan.setBackground(new java.awt.Color(0, 0, 0));
        btncan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btncan.setForeground(new java.awt.Color(204, 204, 204));
        btncan.setText("CLEAR");
        btncan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncanMouseClicked(evt);
            }
        });
        btncan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncanActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        cmbpid.setBackground(new java.awt.Color(204, 204, 204));
        cmbpid.setForeground(new java.awt.Color(204, 204, 204));
        cmbpid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbpid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbpidFocusLost(evt);
            }
        });
        cmbpid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbpidActionPerformed(evt);
            }
        });

        cmbval.setBackground(new java.awt.Color(204, 204, 204));
        cmbval.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chose validity", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cmbval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbvalActionPerformed(evt);
            }
        });

        txtdate.setDateFormatString("y-MM-d");
        txtdate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdateFocusLost(evt);
            }
        });

        txtdoj.setDateFormatString("yyyy-MM-dd");
        txtdoj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdojFocusLost(evt);
            }
        });

        lbl1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl1.setForeground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(149, 149, 149)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtmid, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtmname, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(150, 150, 150)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbpid, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmcon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(cmdw, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(7, 7, 7)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(94, 94, 94)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cmdh, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtdoj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnsave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btndel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btncan)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1081, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdoj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lbl1)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmdw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbpid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsave)
                            .addComponent(btndel)
                            .addComponent(btncan))))
                .addContainerGap(158, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    DataAccess d = new DataAccess();

    private void GetMaxID() {
        try {
            st = DataAccess.con.createStatement();
            rs = st.executeQuery("select ifnull(max(memberid+1),1) as id from membershipmaster");
            if (rs.next()) {
                int id = rs.getInt(1);
                txtmid.setText(Integer.toString(id));
            }
            st.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }

    void search(int id) {
        try {
            String str = "SELECT memberid, membername, Doj, Dob, weight,height,ContactNumber,Email,validity FROM membershipmaster WHERE (memberid =" + id + ")";
          // String str = "select membershipmaster.memberid,membershipmaster.membername,membershipmaster.Doj,membershipmaster.Dob,membershipmaster.weight,membershipmaster.height,packagemaster.PackageName,membershipmaster.ContactNumber,membershipmaster.Email,membershipmaster.validity from membershipmaster inner join packagemaster on packagemaster.PackageId=membershipmaster.memberid";

            PreparedStatement pst = DataAccess.con.prepareStatement(str);
            rs = pst.executeQuery();
            if (rs.next()) {
                txtmid.setText(String.valueOf(rs.getInt("memberid")));
                txtmname.setText(rs.getString("membername"));
                txtmcon.setText((rs.getString("ContactNumber")));
                txtemail.setText((rs.getString("Email")));
                txtdate.setDate((rs.getDate("Dob")));
                txtdoj.setDate((rs.getDate("Doj")));
                //cmbpid.setSelectedItem((rs.getString("PackageId")));
                cmdw.setValue(rs.getInt("weight"));
                cmdh.setValue(rs.getInt("height"));
                   //cmbpid.setSelectedIndex((Int)rs.getString("PackageName"));
                   
                  // cmbpid.setSelectedItem((rs.getString("PackageName")));
                cmbval.setSelectedItem((rs.getString("validity")));

                // cmbMilktype.setSelectedItem((rs.getString("milktype")));
                //btnDelete.setEnabled(true);
                btnsave.setText("UPDATE");
            }
        } catch (NumberFormatException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }

    void Clear() {
        txtmid.setText("");
        txtmname.setText("");
        txtmcon.setText("");
        txtemail.setText("");
        cmbpid.setSelectedIndex(0);
        cmbval.setSelectedIndex(0);
        //cmdh.setEditor(null);
        

        GetMaxID();
        btndel.setEnabled(false);
        btnsave.setText("Save");
    }

    private void BindTable() {
        try {
            String sql = " select membershipmaster.memberid,membershipmaster.membername,membershipmaster.Doj,membershipmaster.Dob,membershipmaster.weight,membershipmaster.height,packagemaster.PackageName,membershipmaster.ContactNumber,membershipmaster.Email from membershipmaster inner join packagemaster on packagemaster.PackageID=membershipmaster.PackageId";
            st = DataAccess.con.createStatement();
            rs = st.executeQuery(sql);
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    public void BindCombo() {
        try {
            String name = "";
            int itemID;
            boolean cnt = true;
            Vector comboboxitem = new Vector();
            st = DataAccess.con.createStatement();
            ResultSet rs = st.executeQuery("SELECT PackageID,PackageName FROM  packagemaster");
            comboboxitem.add(new Item(0, "Select Item"));
            while (rs.next()) {
                cnt = false;
                itemID = rs.getInt("PackageID");
                name = rs.getString("PackageName");
                comboboxitem.add(new Item(itemID, name));
            }
            if (cnt) {
                comboboxitem.add(new Item(0, "No Items Avilable"));
            }

            DefaultComboBoxModel model = new DefaultComboBoxModel(comboboxitem);
            cmbpid.setModel(model);
            cmbpid.addActionListener((ActionListener) this);

        } catch (Exception ex) {
            //  JOptionPane.showMessageDialog(null, ex);
        }
    }
//    void GetPackageName(String name) {
//        try {
//
//            String str = "SELECT * from packagemaster WHERE (PackageName =" + name + ")";
//            PreparedStatement pst = DataAccess.con.prepareStatement(str);
//            rs = pst.executeQuery();
//            if (rs.next()) {
//                //txtID.setText(String.valueOf(rs.getInt("empid")));
//                txtprice.setText(rs.getString("PackagePrice"));
//                //JOptionPane.showMessageDialog(null, "Hello");
//
//            } else {
//                JOptionPane.showMessageDialog(null, "Package not found !");
//            }
//        } catch (NumberFormatException | SQLException ex) {
//            JOptionPane.showMessageDialog(null, ex);
//        }
//
//    }
    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        String ContactNumber=txtmcon.getText();
        
        
        if (txtmid.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Member ID");
            txtmid.setFocusable(true);
        }
        if (txtmname.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Member Name");
            txtmname.setFocusable(true);
        }

        if (txtmcon.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Member Contact");
            txtmcon.setFocusable(true);
        }
        if (txtemail.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Email");
            txtemail.setFocusable(true);
        }
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        doj = sdf.format(txtdate.getDate());
        SimpleDateFormat fds = new SimpleDateFormat("yyyy-MM-dd");
        
        if(ContactNumber.matches("^[0-9] $")||ContactNumber.length()!=10)
        {
            JOptionPane.showMessageDialog(null, "Contact is incorrect!");
        }
        else
        {
            
        
        
        
        dob = fds.format(txtdate.getDate());
        try {

            if (btnsave.getText().equalsIgnoreCase("Save")) {
                st = DataAccess.con.createStatement();

                st.executeUpdate("insert into membershipmaster(membername,Doj,Dob,weight,height,PackageId,ContactNumber,Email,validity)values ('" + txtmname.getText() + "','" + doj + "','" + dob + "','" + cmdw.getValue() + "','" + cmdh.getValue() + "','" + cmbpid.getSelectedIndex() + "','" + txtmcon.getText() + "','" + txtemail.getText() + "','" + cmbval.getSelectedItem() + "')");

                JOptionPane.showMessageDialog(null, "Record Saved Sucessfully........", "membershipmaster", JOptionPane.INFORMATION_MESSAGE);
                st.close();
                BindTable();
            } else {
                st = DataAccess.con.createStatement();

                st.executeUpdate("UPDATE membershipmaster SET membername='" + txtmname.getText() + "',Doj='" + doj + "',Dob='" + dob + "',weight='" + cmdw.getValue() + "',height='" + cmdh.getValue() + "',ContactNumber='" + txtmcon.getText() + "',Email ='" + txtemail.getText() + "',validity='" + cmbval.getSelectedItem() + "' WHERE (memberid=" + txtmid.getText() + ")");
                JOptionPane.showMessageDialog(null, "Record Updated Sucessfully.............", "membershipmaster", JOptionPane.WARNING_MESSAGE);
                st.close();

                BindTable();
                btnsave.setText("Save");
            }
            //Clear();BindTable();BindSearch();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString(), "membershipmaster", JOptionPane.INFORMATION_MESSAGE);
        }
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btncanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncanActionPerformed
        // TODO add your handling code here:t


    }//GEN-LAST:event_btncanActionPerformed

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
        // TODO add your handling code here:
        try {
            st = DataAccess.con.createStatement();
            String sql = "DELETE FROM membershipmaster WHERE memberid = " + txtmid.getText() + "";
            st.executeUpdate(sql);

            Clear();
            BindTable();
            //BindSearch();
            JOptionPane.showMessageDialog(null, "Record Deleted Sucessfully", "Membership Master", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException e1) {

            JOptionPane.showMessageDialog(null, "You can't delete the record....", "Membership Master", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btndelActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        String tblclick = (jTable1.getModel().getValueAt(row, 0).toString());
        int id = Integer.parseInt(tblclick);
        // JOptionPane.showMessageDialog(null, String.valueOf(row));
        search(id);
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtemailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtemailFocusLost
        // TODO add your handling code here:
        d.ValidEmailAddress(txtemail);

    }//GEN-LAST:event_txtemailFocusLost

    private void txtmnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmnameKeyTyped
        // TODO add your handling code here:
        d.EnterOnlycharacter(evt);
    }//GEN-LAST:event_txtmnameKeyTyped

    private void txtmconFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmconFocusLost
        // TODO add your handling code here:
        //d.ValidContactNumber(txtmcon);
        String myStr = txtmcon.getText();
        Length = txtmcon.getText();
        char result = myStr.charAt(0);
        char result1 = myStr.charAt(0);
        char result2 = myStr.charAt(0);
        if (result != '7' && result !='8' && result!='9' && result!='6') {
            JOptionPane.showMessageDialog(null, "Number Should  Start With 6,7,8,9", "Membership Master", JOptionPane.INFORMATION_MESSAGE);
            txtmcon.setEditable(true);
        }else{
        txtmcon.setEditable(true);
        }
    }//GEN-LAST:event_txtmconFocusLost

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Date date = new Date();
        txtdate.setDate(date);

        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDateTime now = LocalDateTime.now();
        doj = dtf.format(now);

        Calendar c = Calendar.getInstance();
        int timeOfDay = c.get(Calendar.HOUR_OF_DAY);

        if (timeOfDay < 12) {
            lbl1.setText("Morning");
        } else {
            lbl1.setText("Evening");

        }
        GetMaxID();
        BindTable();
    }//GEN-LAST:event_formWindowOpened

    private void cmbpidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbpidFocusLost
       // TODO add your handling code here:
        /*if (cmbpid.getSelectedItem().equals("")) {
           JOptionPane.showMessageDialog(null, "Enter Producer Number");
       } else {
           String name = (String) cmbpid.getSelectedItem();
           GetPackageName(name);
       }*/
    }//GEN-LAST:event_cmbpidFocusLost

    private void txtmconKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmconKeyTyped
        // TODO add your handling code here:
        
     
        

    }//GEN-LAST:event_txtmconKeyTyped

    private void txtmconKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmconKeyReleased

    }//GEN-LAST:event_txtmconKeyReleased

    private void txtdateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdateFocusLost
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtdateFocusLost

    private void txtdojFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdojFocusLost
        // TODO add your handling code here:
         String date = ((JTextField)txtdoj.getDateEditor().getUiComponent()).getText();
         String b[] = date.split("/");
         int day = Integer.parseInt(b[0]);
         int mn = Integer.parseInt(b[1]);
         int yr = Integer.parseInt(b[2]);
         LocalDate l =LocalDate.of(yr,mn,day);
         LocalDate c = LocalDate.now();
         int res = Period.between(l,c).getYears();
         if(res<15){
              JOptionPane.showMessageDialog(null, "You Are Under Age", "Membership Master", JOptionPane.INFORMATION_MESSAGE);
         }
    }//GEN-LAST:event_txtdojFocusLost

    private void txtmconKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmconKeyPressed
        // TODO add your handling code here:
     
        String mobileno=txtmcon.getText();
        int length=mobileno.length();
        char c = evt.getKeyChar();
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if(length<10){
            txtmcon.setEditable(true);
            }
            else{
            txtmcon.setEditable(false);
            }
        }else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE ||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
            txtmcon.setEditable(true);
            }else{
            txtmcon.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtmconKeyPressed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void btncanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncanMouseClicked
        // TODO add your handling code here:
        Clear();
    }//GEN-LAST:event_btncanMouseClicked

    private void txtmconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmconActionPerformed

    private void cmbvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbvalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbvalActionPerformed

    private void cmbpidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbpidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbpidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
            throws SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(membershipform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(membershipform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(membershipform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(membershipform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        DataAccess.dbConnect();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new membershipform().setVisible(true);
            }
        });
    }

    {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(membershipform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(membershipform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(membershipform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(membershipform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncan;
    private javax.swing.JButton btndel;
    private javax.swing.JButton btnsave;
    private javax.swing.JComboBox<String> cmbpid;
    private javax.swing.JComboBox<String> cmbval;
    private javax.swing.JSpinner cmdh;
    private javax.swing.JSpinner cmdw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl1;
    private com.toedter.calendar.JDateChooser txtdate;
    private com.toedter.calendar.JDateChooser txtdoj;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtmcon;
    private javax.swing.JTextField txtmid;
    private javax.swing.JTextField txtmname;
    // End of variables declaration//GEN-END:variables
}
