/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author harga
 */
public class simplereport extends javax.swing.JFrame {

    
    public simplereport() {
        initComponents();
         this.setDefaultCloseOperation(simplereport.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbreport = new javax.swing.JComboBox<>();
        btnshow = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(246, 139, 144));
        setForeground(java.awt.Color.pink);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("View Report :");

        cmbreport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Member", "Employee", "Employee Payment", "Expense", "Equipment", "Package" }));

        btnshow.setBackground(new java.awt.Color(255, 0, 0));
        btnshow.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnshow.setText("SHOW");
        btnshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Simple Report");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbreport, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(btnshow, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(66, 99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbreport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnshow)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowActionPerformed
        // TODO add your handling code here:
        if(cmbreport.getSelectedIndex()==0){
             try
            {
                
               String reportSource="E:\\JSP\\GymManagementSystem\\src\\reports\\membership.jrxml";
                JasperDesign jd = JRXmlLoader.load(reportSource);
            
               JasperReport jr = JasperCompileManager.compileReport(jd);
                JasperPrint jp=JasperFillManager.fillReport(jr,null,DataAccess.con);
                JasperViewer.viewReport(jp);
            }
            catch(JRException ex)
            {
                JOptionPane.showMessageDialog(null,ex.getMessage(),"Expense List",JOptionPane.WARNING_MESSAGE);
            }
        }
        else if(cmbreport.getSelectedIndex()==1){
             try
            {
                
               String reportSource="E:\\JSP\\GymManagementSystem\\src\\reports\\employee.jrxml";
                JasperDesign jd = JRXmlLoader.load(reportSource);
            
               JasperReport jr = JasperCompileManager.compileReport(jd);
                JasperPrint jp=JasperFillManager.fillReport(jr,null,DataAccess.con);
                JasperViewer.viewReport(jp);
            }
            catch(JRException ex)
            {
                JOptionPane.showMessageDialog(null,ex.getMessage(),"Expense List",JOptionPane.WARNING_MESSAGE);
            }
        }
        else if(cmbreport.getSelectedIndex()==2){
             try
            {
                
               String reportSource="E:\\JSP\\GymManagementSystem\\src\\reports\\employeepayment.jrxml";
                JasperDesign jd = JRXmlLoader.load(reportSource);
            
               JasperReport jr = JasperCompileManager.compileReport(jd);
                JasperPrint jp=JasperFillManager.fillReport(jr,null,DataAccess.con);
                JasperViewer.viewReport(jp);
            }
            catch(JRException ex)
            {
                JOptionPane.showMessageDialog(null,ex.getMessage(),"Expense List",JOptionPane.WARNING_MESSAGE);
            }
        }
        else if(cmbreport.getSelectedIndex()==3){
             try
            {
                
               String reportSource="E:\\JSP\\GymManagementSystem\\src\\reports\\expense.jrxml";
                JasperDesign jd = JRXmlLoader.load(reportSource);
            
               JasperReport jr = JasperCompileManager.compileReport(jd);
                JasperPrint jp=JasperFillManager.fillReport(jr,null,DataAccess.con);
                JasperViewer.viewReport(jp);
            }
            catch(JRException ex)
            {
                JOptionPane.showMessageDialog(null,ex.getMessage(),"Expense List",JOptionPane.WARNING_MESSAGE);
            }
        }else if(cmbreport.getSelectedIndex()==4){
             try
            {
                
               String reportSource="E:\\JSP\\GymManagementSystem\\src\\reports\\equipment.jrxml";
                JasperDesign jd = JRXmlLoader.load(reportSource);
            
               JasperReport jr = JasperCompileManager.compileReport(jd);
                JasperPrint jp=JasperFillManager.fillReport(jr,null,DataAccess.con);
                JasperViewer.viewReport(jp);
            }
            catch(JRException ex)
            {
                JOptionPane.showMessageDialog(null,ex.getMessage(),"Expense List",JOptionPane.WARNING_MESSAGE);
            }
        }else if(cmbreport.getSelectedIndex()==5){
             try
            {
                
               String reportSource="E:\\JSP\\GymManagementSystem\\src\\reports\\Package.jrxml";
                JasperDesign jd = JRXmlLoader.load(reportSource);
            
               JasperReport jr = JasperCompileManager.compileReport(jd);
                JasperPrint jp=JasperFillManager.fillReport(jr,null,DataAccess.con);
                JasperViewer.viewReport(jp);
            }
            catch(JRException ex)
            {
                JOptionPane.showMessageDialog(null,ex.getMessage(),"Expense List",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnshowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(simplereport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(simplereport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(simplereport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(simplereport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        DataAccess.dbConnect();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new simplereport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnshow;
    private javax.swing.JComboBox<String> cmbreport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
